data:
  name: gist
  data_dir: datasets
  image_root: datasets_full
  metadata: metadata_full.csv
  split: splits_balanced.json
  tiles: tiles.pkl
  intrinsics: intrinsics.json
  target_csv: null
  require_target: false
  teacher_scores_dir: null
  require_teacher_scores: false
  scene: gist_abc
  sequence: single
  target_lat_col: target_lat
  target_lon_col: target_lon
  target_yaw_col: target_yaw
  gps_lat_col: gps_lat
  gps_lon_col: gps_lon
  loading:
    train:
      batch_size: 8
      num_workers: 16
    val:
      batch_size: 8
      num_workers: 16
    test:
      batch_size: 1
      num_workers: 0
  num_classes:
    areas: 7
    ways: 10
    nodes: 33
  pixel_per_meter: 2
  crop_size_meters: 64
  max_init_error: 0
  init_from_gps: true
  add_map_mask: true
  mask_radius: 64
  resize_image: 512
  pad_to_square: true
  rectify_pitch: true
  augmentation:
    rot90: false
    flip: false
    image:
      apply: false
model:
  image_encoder:
    name: feature_extractor_v2
    backbone:
      encoder: resnet101
      pretrained: false
      output_dim: 128
      num_downsample: null
      remove_stride_from_first_conv: false
  name: orienternet
  latent_dim: 128
  matching_dim: 8
  z_max: 32
  x_max: 32
  pixel_per_meter: 2
  scale_range:
  - 1
  - 9
  num_scale_bins: 33
  num_rotations: 64
  padding_matching: replicate
  norm_depth_scores: false
  normalize_scores_by_dim: false
  normalize_scores_by_num_valid: true
  normalize_features: false
  map_encoder:
    embedding_dim: 16
    output_dim: 8
    num_classes:
      areas: 7
      ways: 10
      nodes: 33
    backbone:
      encoder: vgg19
      pretrained: false
      output_scales:
      - 0
      num_downsample: 3
      decoder:
      - 128
      - 64
      - 64
      padding: replicate
    unary_prior: true
  bev_net:
    num_blocks: 4
    latent_dim: 128
    output_dim: 8
    confidence: true
experiment:
  name: gist_abc_balanced_no_rectify_lr1e-5_init16_from_laststep_ep20_xybest
  root: experiments/
  gpus: 1
  seed: 0
training:
  elastic: false
  lr: 1.0e-05
  lr_scheduler: null
  finetune_from_checkpoint: experiments/gist_abc_balanced_no_rectify_lr1e-5_init16_ep40_top1/last-step.ckpt
  trainer:
    val_check_interval: 5000
    log_every_n_steps: 100
    limit_val_batches: 1000
    max_epochs: 20
    devices: 1
    max_steps: -1
    accumulate_grad_batches: 4
  checkpointing:
    monitor: val/xy_max_error
    save_top_k: 3
    mode: min
